---
- name: Include vars
  hosts: all
  vars_files:
    - "group_vars/all/ssh_login.yml"
    - "group_vars/clickhouse/clickhouse_ip.yml"
    - "group_vars/lighthouse/lighthouse_ip.yml"
    - "group_vars/vector/vector_ip.yml"
- name: Install Vector
  tags: vector
  hosts: vector
  handlers:
    - name: Restart service Vector
      ansible.builtin.systemd:
        name: vector
        daemon_reload: true
        state: restarted
      become: true
  tasks:
    - name: Upload Vector
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
        dest: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
        mode: "0755"
        timeout: 60
        force: true
        validate_certs: false
      register: get_vector
      until: get_vector is succeeded
    - name: Create directrory for Vector
      become: true
      ansible.builtin.file:
        state: directory
        path: "{{ vector_home }}/vector"
        mode: "0755"
    - name: Extract Vector in the installation directory
      become: true
      ansible.builtin.unarchive:
        copy: false
        src: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
        dest: "{{ vector_home }}/vector"
        extra_opts: [--strip-components=2]
        creates: "{{ vector_home }}/vector/bin"
    - name: Set environment Vector
      become: true
      ansible.builtin.template:
        src: templates/vector.sh.j2
        dest: /etc/profile.d/vector.sh
        mode: "0755"
    - name: Create directrory /etc/vector for Vector
      become: true
      ansible.builtin.file:
        state: directory
        path: /etc/vector
        mode: "0755"
    - name: Create directrory /var/lib/vector for Vector
      become: true
      ansible.builtin.file:
        state: directory
        path: /var/lib/vector
        mode: "0755"
    - name: Copy template file for Vector
      become: true
      ansible.builtin.copy:
        src: templates/vector.yaml
        dest: "/etc/vector/vector.yaml"
        mode: "0755"
      notify: Restart service Vector
    - name: Copy vector.service for systemd
      become: true
      ansible.builtin.template:
        src: templates/vector.service.j2
        dest: "/etc/systemd/system/vector.service"
        mode: "0755"
    - name: Start service Vector
      ansible.builtin.systemd:
        name: vector
        daemon_reload: true
        state: started
      become: true
- name: Install Clickhouse
  tags: clickhouse
  hosts: clickhouse
  tasks:
    - name: Install dependent packages for Clickhouse
      become: true
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - dirmngr
    - name: Add repository and apt-key for Clickhouse
      block:
        - name: Install apt-key for Clickhouse
          become: true
          ansible.builtin.apt_key:
            keyserver: hkp://keyserver.ubuntu.com:80
            id: 8919F6BD2B48D754
        - name: Add repository for Clickhouse
          become: true
          ansible.builtin.apt_repository:
            repo: deb https://packages.clickhouse.com/deb stable main
            state: present
            filename: clickhouse
    - name: Install Clickhouse packages
      become: true
      ansible.builtin.apt:
        name:
          - clickhouse-common-static
          - clickhouse-server
          - clickhouse-client
        update_cache: true
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
    - name: Start Clickhouse service
      become: true
      ansible.builtin.systemd:
        name: clickhouse-server
        daemon_reload: true
        state: started
- name: Install Lighthouse
  tags: lighthouse
  hosts: lighthouse
  handlers:
    - name: Restart service nginx
      ansible.builtin.systemd:
        name: nginx
        daemon_reload: true
        state: restarted
      become: true
  tasks:
    - name: Install unzip
      become: true
      ansible.builtin.apt:
        name: unzip
    - name: Extract all ZIP files from git Lighthouse
      become: true
      ansible.builtin.git:
        repo: "https://github.com/VKCOM/lighthouse.git"
        version: master
        dest: /opt
    - name: Install nginx
      become: true
      ansible.builtin.apt:
        name: nginx
    - name: Template index.html lighthouse
      become: true
      ansible.builtin.template:
        src: templates/light_index.j2
        dest: /etc/nginx/sites-available/default
        mode: "0755"
      notify: Restart service nginx
    - name: Start nginx demon
      become: true
      ansible.builtin.systemd:
        name: nginx
        daemon_reload: true
        state: started
