#cloud-config
users:
  - name: ${username}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
# package_update: true
# package_upgrade: false
# packages:
#  - vim
#  - nginx
# runcmd: []